---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-controller
  namespace: default
spec:
  isCA: true
  commonName: k8s-controller
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - k8s-controller.default.svc
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mutant-issuer
  namespace: default
spec:
  ca:
    secretName: root-secret
