kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: k8s-controller
  annotations:
    cert-manager.io/inject-ca-from: default/k8s-controller
webhooks:
  - name: k8s-controller.default.svc
    clientConfig:
      service:
        namespace: default
        name: k8s-controller
        path: /mutate
    rules:
      - apiGroups:
          - "apps"
        apiVersions:
          - "v1"
        resources:
          - "deployments"
        operations:
          - "CREATE"
        scope: Namespaced
    sideEffects: None
    admissionReviewVersions:
      - "v1"
